spring:
  application:
    name: properties-management-svc

  data:
    mongodb:
      database: ${PROPERTIES_DB:acma}
      host: ${PROPERTIES_DB_HOST:localhost}
      port: ${PROPERTIES_DB_PORT:27017}
      auto-index-creation: true
      
      

server:
  port: 7101
  
properties: 
  management: 
     collections: 
       name: ${PROPERTIES_COLLECTIONS_NAME:properties-management}
       
       
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

  

